#!/usr/bin/env bash
#
# wigglydots - wigglytuff's configurator <wiggly@wigglytuff.org>
#
# mescaline is created by netzverweigerer - http://github.com/netzverweigerer/
#

# parameter expansion to extract the scripts home directory
script="${0%/*}"
home="$(readlink -f $script)"
cd "$home"

# print a message
msg () {
  printf "[wigglytuff] "
  printf "$@ \n"
}

wig="[wigglytuff]"

# run mescaline installer
msg 'running mescaline installer...'
if [ -e "$HOME/.mescaline" ]; then
  rm -rf "$HOME/.mescaline"
fi
mv "$HOME/.zshrc" "$HOME/.zshrc.pre-mescaline"
sh ./mescaline/install.sh || msg 'mescaline install failed. continuing anyway.'

# create .wigglytuff directory
msg 'creating .wigglytuff directory...'
rm -rf "$HOME/.wigglytuff"
mkdir "$HOME/.wigglytuff"
rsync -a . "$HOME/.wigglytuff"

# backup old dotfiles and create new symlinks
msg 'creating dotfile symlinks...'
if [ -e "$HOME/.vimrc" ]; then
  mv "$HOME/.vimrc" "$HOME/.vimrc-prewiggly"
fi
if [ -e "$HOME/.tmux.conf" ]; then
  mv "$HOME/.tmux.conf" "$HOME/.tmux.conf-prewiggly"
fi
#if [ -e "$HOME/.zshrc" ]; then
#  mv "$HOME/.zshrc" "$HOME/.zshrc-prewiggly"
#fi
ln -s "$HOME/.wigglytuff/dotfiles/.vimrc" "$HOME/.vimrc"
ln -s "$HOME/.wigglytuff/dotfiles/.tmux.conf" "$HOME/.tmux.conf"
#ln -s "$HOME/.wigglytuff/dotfiles/.zshrc" "$HOME/.zshrc"

# append wiggly's aliases to .zshrc
msg 'appending aliases...'
cat "$HOME/.wigglytuff/dotfiles/.alias" >> "$HOME/.zshrc"

# setup options
if [ -e "$HOME/.mescaline" ]; then
  read -r -p "$wig remove @hostname from powerline prompt? (y/N) " response
  case $response in
    [yY][eE][sS]|[yY])
        sed -ie "s/ + \"@\" + hostname//g" "$HOME/.mescaline/mescaline"
        ;;
  esac
  read -r -p "$wig set basic powerline shell prompt colours? (y/N) " response
  case $response in
    [yY][eE][sS]|[yY])
		msg "don't worry if you fuck this up, just run the installer again."
		msg "for colour codes, see http://bit.ly/1EEOlar"
		read -r -p "$wig foreground: " foreground
		read -r -p "$wig background: " background
		sed -ie "s/user_fg = 15/user_fg = $foreground/g" "$HOME/.mescaline/mescaline"
		sed -ie "s/124/$background/g" "$HOME/.mescaline/mescaline"
        ;;
  esac
fi

# appends apikeys from dotfiles/apikeys to ~/.zshrc
if [ -e "./dotfiles/apikeys" ]; then
  msg 'appending api keys...'
  cat "./dotfiles/apikeys" >> "$HOME/.zshrc"
fi
msg 'done.'
