#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import subprocess
import sys
import re
import getpass
import socket

encoding = sys.getdefaultencoding()

def warn(msg):
    print('[mescaline-zsh] ', msg)

class Color:
    path_bg = 236
    path_fg = 15
    cwd_fg = 254
    separator_fg = 244
    repo_clean_bg = 148
    repo_clean_fg = 0
    repo_dirty_bg = 161
    repo_dirty_fg = 15
    cmd_passed_bg = 236
    cmd_passed_fg = 242
    cmd_failed_bg = 161
    cmd_failed_fg = 15
    svn_changes_bg = 148
    svn_changes_fg = 22
    virtual_env_bg = 75
    virtual_env_fg = 27

class Mescaline:
    symbols = {
        'separator': '',
        'separator_thin': ''
    }
    reset = ' %f%k'

    def __init__(self):
        self.separator = Mescaline.symbols['separator']
        self.separator_thin = Mescaline.symbols['separator_thin']
        self.segments = []

    def color(self, prefix, code):
        if prefix == '38':
            return '%%F{%s}' % code
        elif prefix == '48':
            return '%%K{%s}' % code

    def fgcolor(self, code):
        return self.color('38', code)

    def bgcolor(self, code):
        return self.color('48', code)

    def append(self, segment):
        self.segments.append(segment)

    def draw(self):
        return (''.join((s[0].draw(self, s[1]) for s in zip(self.segments, self.segments[1:] + [None]))) + self.reset)

class Segment:
    def __init__(self, mescaline, content, fg, bg, separator=None, separator_fg=None):
        self.mescaline = mescaline
        self.content = content
        self.fg = fg
        self.bg = bg
        self.separator = separator or mescaline.separator
        self.separator_fg = separator_fg or bg

    def draw(self, mescaline, next_segment=None):
        if next_segment:
            separator_bg = mescaline.bgcolor(next_segment.bg)
        else:
            separator_bg = mescaline.reset

        return ''.join((
            mescaline.fgcolor(self.fg),
            mescaline.bgcolor(self.bg),
            self.content,
            separator_bg,
            mescaline.fgcolor(self.separator_fg),
            self.separator))

def add_cwd_segment(mescaline, cwd, maxdepth):
    home = os.getenv('HOME')
    cwd = os.getenv('PWD')

    if cwd.find(home) == 0:
        cwd = cwd.replace(home, '~', 1)

    if cwd[0] == '/':
        cwd = cwd[1:]

    names = cwd.split('/')
    if len(names) > maxdepth:
        names = names[:2] + ['⋯ '] + names[2 - maxdepth:]

    for n in names[:-1]:
        mescaline.append(Segment(mescaline, ' %s ' % n, Color.path_fg, Color.path_bg, mescaline.separator_thin, Color.separator_fg))

    mescaline.append(Segment(mescaline, ' %s ' % names[-1], Color.cwd_fg, Color.path_bg))

def get_hg_status():
    has_modified_files = False
    has_untracked_files = False
    has_missing_files = False
    output = subprocess.Popen(['hg', 'status'], stdout=subprocess.PIPE).communicate()[0]
    for line in output.split('\n'):
        if line == '':
            continue
        elif line[0] == '?':
            has_untracked_files = True
        elif line[0] == '!':
            has_missing_files = True
        else:
            has_modified_files = True
    return has_modified_files, has_untracked_files, has_missing_files

def add_hg_segment(mescaline, cwd):
    branch = os.popen('hg branch 2> /dev/null').read().rstrip()
    if len(branch) == 0:
        return False
    bg = Color.repo_clean_bg
    fg = Color.repo_clean_fg
    has_modified_files, has_untracked_files, has_missing_files = get_hg_status()
    if has_modified_files or has_untracked_files or has_missing_files:
        bg = Color.repo_dirty_bg
        fg = Color.repo_dirty_fg
        extra = ''
        if has_untracked_files:
            extra += '+'
        if has_missing_files:
            extra += '!'
        branch += (' ' + extra if extra != '' else '')
    mescaline.append(Segment(mescaline, ' %s ' % branch, fg, bg))
    return True

def get_git_status():
    has_pending_commits = True
    has_untracked_files = False
    origin_position = ""
    output = subprocess.Popen(['git', 'status', '-unormal'], stdout=subprocess.PIPE).communicate()[0]
    for line in output.decode(encoding).split('\n'):
        origin_status = re.findall("Your branch is (ahead|behind).*?(\d+) comm", line)
        if len(origin_status) > 0:
            origin_position = " %d" % int(origin_status[0][1])
            if origin_status[0][0] == 'behind':
                origin_position += '↓'
            elif origin_status[0][0] == 'ahead':
                origin_position += '↑'

        if line.find('nothing to commit') >= 0:
            has_pending_commits = False
        if line.find('Untracked files') >= 0:
            has_untracked_files = True
    return has_pending_commits, has_untracked_files, origin_position

def add_git_segment(mescaline, cwd):
    p = subprocess.Popen(['git', 'symbolic-ref', '-q', 'HEAD'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    out, err = p.communicate()

    if 'Not a git repo' in err.decode(encoding):
        return False

    if out:
        branch = out[len('refs/heads/'):].rstrip()
    else:
        branch = '(Detached)'

    branch = branch.decode(encoding)
    has_pending_commits, has_untracked_files, origin_position = get_git_status()
    branch += origin_position
    if has_untracked_files:
        branch += ' +'

    bg = Color.repo_clean_bg
    fg = Color.repo_clean_fg

    if has_pending_commits:
        bg = Color.repo_dirty_bg
        fg = Color.repo_dirty_fg

    mescaline.append(Segment(mescaline, ' %s ' % branch, fg, bg))
    return True

def add_svn_segment(mescaline, cwd):
    if not os.path.exists(os.path.join(cwd, '.svn')):
        return
    '''svn info:
        First column: Says if item was added, deleted, or otherwise changed
        ' ' no modifications
        'A' Added
        'C' Conflicted
        'D' Deleted
        'I' Ignored
        'M' Modified
        'R' Replaced
        'X' an unversioned directory created by an externals definition
        '?' item is not under version control
        '!' item is missing (removed by non-svn command) or incomplete
         '~' versioned item obstructed by some item of a different kind
    '''
    try:
        p1 = subprocess.Popen(['svn', 'status'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        p2 = subprocess.Popen(['grep', '-c', '^[ACDIMRX\\!\\~]'], stdin=p1.stdout, stdout=subprocess.PIPE)
        output = p2.communicate()[0].strip()
        if len(output) > 0 and int(output) > 0:
            changes = output.strip()
            mescaline.append(Segment(mescaline, ' %s ' % changes, Color.svn_changes_fg, Color.svn_changes_bg))
    except OSError:
        return False
    except subprocess.CalledProcessError:
        return False
    return True

def add_repo_segment(mescaline, cwd):
    for add_repo_segment in [add_git_segment, add_svn_segment, add_hg_segment]:
        try:
            if add_repo_segment(p, cwd):
                return
        except subprocess.CalledProcessError:
            pass
        except OSError:
            pass
def add_virtual_env_segment(mescaline, cwd):
    env = os.getenv("VIRTUAL_ENV")
    if env is None:
        return False
    env_name = os.path.basename(env)
    bg = Color.virtual_env_bg
    fg = Color.virtual_env_fg
    mescaline.append(Segment(mescaline, ' virtualenv: %s ' % env_name, fg, bg))
    return True

def add_username_segment(mescaline, username):
    bg = Color.virtual_env_bg
    fg = Color.virtual_env_fg
    mescaline.append(Segment(mescaline, ' %s ' % username, fg, bg))
    return True

def add_root_indicator(mescaline, error):
    bg = Color.cmd_passed_bg
    fg = Color.cmd_passed_fg
    if int(error) != 0:
        fg = Color.cmd_failed_fg
        bg = Color.cmd_failed_bg
    mescaline.append(Segment(mescaline, '', fg, bg))

def get_valid_cwd():
    try:
        cwd = os.getcwd()
    except:
        cwd = os.getenv('PWD')
        parts = cwd.split(os.sep)
        up = cwd
        while parts and not os.path.exists(up):
            parts.pop()
            up = os.sep.join(parts)
        try:
            os.chdir(up)
        except:
            warn("Your current directory is invalid.")
            sys.exit(1)
        warn("Your current directory is invalid. Lowest valid directory: " + up)
    return cwd

def get_username():
    return getpass.getuser()
def get_hostname():
    return socket.gethostname()

if __name__ == '__main__':
    p = Mescaline()

    username = get_username()
    hostname = get_hostname()
    txt = username + "@" + hostname
    add_username_segment(p, txt)

    cwd = get_valid_cwd()
    add_virtual_env_segment(p, cwd)
    add_cwd_segment(p, cwd, 5)
    add_repo_segment(p, cwd)
    add_root_indicator(p, 0)

    if sys.version_info[0] < 3:
        sys.stdout.write(p.draw().encode('utf-8'))
    else:
        sys.stdout.buffer.write(p.draw().encode('utf-8'))


