#!/usr/bin/env bash
#
# $1 is a URL. then it uploads that image to wigglytuff.org and spits the url
#

wget "$1" -O tmp -q || cp "$1" tmp
rsync tmp fubinaca:"$HOME/wigglytuff.org/images/tmp" -aq --progress
echo "$1 has been uploaded to https://wigglytuff.org/images/tmp"
rm tmp

